### ISSUE TITLE
rngd - "[hwrng ]: Initialization Failed" when configured to use /dev/TrueRNG 

### ISSUE THREAD

**Issue by caedmon-kitty** [euler357/TrueRNG#1]
Fedora Linux version 35
rngd --version
rngd 6.14

I have been using TrueRNG V3 on several versions of Fedora without problems.  However on version 35 it fails.

I have added "-r /dev/TrueRNG" to /etc/sysconfig/rngd.
When restarting rngd.service via systemctl I see:
Aug 30 15:34:02 cowboys.cisco.com rngd[31674]: Initializing available sources
Aug 30 15:34:02 cowboys.cisco.com rngd[31674]: [hwrng ]: Initialization Failedt

"python truerng_test.py" shows Success
/dev/TrueRNG exists and is a symlink to /dev/ttyACM0 which also exists.

Is rngd 6.14 able to utilize TrueRNG V3?
...

**Comment by euler357** [comment]
If python truerng_test.py works, then the issue is either in your permissions or in the latest version of rngd.  I'd first check your permissions on /dev/TrueRNG and /dev/ttyACM0

rngd 6.15 works for me in Ubuntu 22.04 (downloaded from github and rebuilt)


![rngd_6 15 screenshot](https://user-images.githubusercontent.com/3341168/187569282-1dca5c56-cc35-49b0-96cc-dbcdbee4a4b9.png)

**Comment by euler357** [comment]
Verified to work with the latest rngd 6.15

**Comment by caedmon-kitty** [comment]
Is this correct?

ls -l /dev/TrueRNG0
lrwxrwxrwx. 1 root root 7 Aug 31 11:11 /dev/TrueRNG0 -> ttyACM0
ls -l /dev/ttyACM0
crw-rw-rw-. 1 root dialout 166, 0 Aug 31 11:11 /dev/ttyACM0

**Comment by euler357** [comment]
The latest udev rules number the TrueRNG device nodes in case you have more than 1 TrueRNG device

**Comment by caedmon-kitty** [comment]
Found the problem.  selinux prevents rngd from accessing the /dev/ttyACM0 device.
#first the working device
ls -Z /dev/hwrng
system_u:object_r:random_device_t:s0 /dev/hwrng
#Now the device /dev/TrueRNG points to
ls -Z /dev/ttyACM0
system_u:object_r:tty_device_t:s0 /dev/ttyACM0
#Change the selinux context of ttyACM0 to match hwrng
sudo chcon --reference=/dev/hwrng /dev/ttyACM0
#Make sure the context change worked
ls -Z /dev/ttyACM0
system_u:object_r:random_device_t:s0 /dev/ttyACM0

#Now restart rngd
systemctl restart rngd
systemctl status rngd
...
Aug 31 14:05:36 cowboys.cisco.com rngd[221141]: [hwrng ]: Initialized
...
#It worked.

I need to figure out how to perform the chcon command on device insertion.  Maybe point to a script instead of invoking /bin/stty and chcon directly.
