### ISSUE TITLE
udev rules set baud rate to undocumented number

### ISSUE THREAD

**Issue by oclyke** [euler357/TrueRNG#3]
I cannot seem to understand why the udev rules set the `speed` option to 3000000. Is this a typo where it is meant to be in 300? Does it need to be set at all if the device is assumed to already be in "normal" mode and this is clearly not the "knock sequence?"

Everything seems to be working for me as expected otherwise, including the ability to switch modes.

Thanks for the nice hardware!

**Comment by ubldit** [comment]
it's setting the baud rate to 3mbit, but since its a virtual serial port, it doesn't do anything but tell the device the baud rate.  It doesn't really affect anything, but it doesn't hurt it either.

**Comment by oclyke** [comment]
Great, thanks for confirming that! One more question - does the device have persistent memory to maintain the mode across power cycles? Or does the mode always begin in one mode - say "normal" for instance?

Apologies in case I am missing some documentation that points this stuff out!

Edit:
In my testing I keep finding that the device seems to be in the wrong mode or something - at boot-up I run `less -f /dev/TrueRNG0` and see that the file ends very quickly (only a few hundred or thousand bytes). I have to manually reconfigure the device using `stty` to perform the knock sequence.

**Comment by euler357** [comment]
The device resets to the default state at every power cycle.  I'd recommend that you use the python tools here and not "less" to stream from the device.  If you must read directly from the command line then use dd or cat
