### ISSUE TITLE
Running python scripts on Ubuntu 22.04 requires root permission

### ISSUE THREAD

**Issue by Kaiyangshi-Ito** [euler357/TrueRNG#4]
If I don't execute them as root (without using sudo), I encounter errors. Could this be related to USB device access on the system? Is it possible to address this by modifying the scripts? Thanks.

**Comment by euler357** [comment]
You likely haven't set the permissions on the device node or the link to it correctly.

I believe that the udev rule should do this for you if you installed it per the instructions.
