### ISSUE TITLE
Can the TrueRNG be used on Mac OS?

### ISSUE THREAD

**Issue by Kaiyangshi-Ito** [euler357/TrueRNG#5]
I tried to use the device on my M1 Macbook, with or without root permission, it won't work in either case. Can supposedly for Mac OS be added? Thanks.

**Comment by euler357** [comment]
None of the developers currently own a Mac.  We have had other users try it and it worked fine for them.  It should enumerate as a standard USB CDC device (virtual serial port) using a default driver.  You just need to find where it mounts.
