### ISSUE TITLE
Use the device for GPG/SSH key generation

### ISSUE THREAD

**Issue by Kaiyangshi-Ito** [euler357/TrueRNG#6]
Can some instructions be added to use the TrueRNG to generate GPG and SSH keys? It would be very helpful to add these instructions.

**Comment by euler357** [comment]
If you install rngd (rng-tools) and point it to the TrueRNG (instructions here:  https://ubld.it/products/support/truerng-install-guide) then it will seed the random number pool in linux that gpg should pull from (/dev/random).
