### ISSUE TITLE
Issues regarding installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by Kaiyangshi-Ito** [euler357/TrueRNG#7]
I followed the instructions on https://ubld.it/products/support/truerng-install-guide, and I got in a few issues:

1. For Ubuntu Linux Installation 4, it says:
Verify /dev/TrueRNG device appears by typing
ls -l /dev/TrueRNG

However, mine only works for  ls -l /dev/TrueRNG0, I believe this is due to in `99-TrueRNG.rules`, it says `"TrueRNG%n"` instead of `"TrueRNG"`, changing this part makes `ls -l /dev/TrueRNG` work.

2. For Installing rng-tools on Ubuntu (optional) 3, it says:
Make sure rng-tools will autostart
sudo update-rc.d rng-tools enable

However, I got:
sudo update-rc.d rng-tools enable
update-rc.d: error: cannot find a LSB script for rng-tools

Note that in previous steps, I also had:
sudo apt-get install rng-tools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'rng-tools-debian' instead of 'rng-tools'
rng-tools-debian is already the newest version (2.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by euler357** [comment]
#1 - yes, the script was changed to allow for multiple TrueRNG units.  Units should appear as /dev/TrueRNG0 etc.

#2 This is not a problem with the TrueRNG or TrueRNG scripts provided here.  I recommend that you address this with rng-tools support. (https://github.com/nhorman/rng-tools)
